package com.recruva.enums;

public enum Permission {
    MANAGE_ORGANIZATION,
    MANAGE_MEMBERS,
    CREATE_JOB,
    UPDATE_JOB,
    VIEW_JOB,
    MANAGE_CANDIDATES,
    MANAGE_APPLICATIONS,
    VIEW_APPLICATIONS,
    MANAGE_INTERVIEWS,
    VIEW_INTERVIEWS,
    CONDUCT_INTERVIEW
}
